apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: skxk6rnce-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:aa23d63659f06c840b5766455b1c4c9b15367606@sha256:b7294c42aae972c3315bb8756ca3d79e6b6893873b1c49ec2a1e7e8e3b9b57af
          name: container-image
