apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: skxk6rnce-python
  janus-idp.io/tekton: skxk6rnce-python
  backstage.io/kubernetes-id: skxk6rnce-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: skxk6rnce-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
